<option value="-">Escolha a Unidade Temática</option>
<option value="Língua Portuguesa (EF) - Leitura">Língua Portuguesa (EF) - Leitura</option>
<option value="Língua Portuguesa (EF) - Produção de textos">Língua Portuguesa (EF) - Produção de textos</option>
<option value="Língua Portuguesa (EF) - Oralidade">Língua Portuguesa (EF) - Oralidade</option>
<option value="Língua Portuguesa (EF) - Análise linguística/semiótica">Língua Portuguesa (EF) - Análise linguística/semiótica</option>
<option value="Língua Portuguesa (EM) - Leitura e interpretação">Língua Portuguesa (EM) - Leitura e interpretação</option>
<option value="Língua Portuguesa (EM) - Produção de textos">Língua Portuguesa (EM) - Produção de textos</option>
<option value="Língua Portuguesa (EM) - Literatura">Língua Portuguesa (EM) - Literatura</option>
<option value="Língua Portuguesa (EM) - Educação midiática">Língua Portuguesa (EM) - Educação midiática</option>
<option value="Matemática (EF) - Números">Matemática (EF) - Números</option>
<option value="Matemática (EF) - Álgebra">Matemática (EF) - Álgebra</option>
<option value="Matemática (EF) - Geometria">Matemática (EF) - Geometria</option>
<option value="Matemática (EF) - Grandezas e Medidas">Matemática (EF) - Grandezas e Medidas</option>
<option value="Matemática (EF) - Probabilidade e Estatística">Matemática (EF) - Probabilidade e Estatística</option>
<option value="Matemática (EM) - Números e Álgebra">Matemática (EM) - Números e Álgebra</option>
<option value="Matemática (EM) - Geometria">Matemática (EM) - Geometria</option>
<option value="Matemática (EM) - Grandezas e Medidas">Matemática (EM) - Grandezas e Medidas</option>
<option value="Matemática (EM) - Probabilidade e Estatística">Matemática (EM) - Probabilidade e Estatística</option>
<option value="Matemática (EM) - Matemática Financeira">Matemática (EM) - Matemática Financeira</option>

<option value="Ciências (EF) - Matéria e Energia">Ciências (EF) - Matéria e Energia</option>
<option value="Ciências (EF) - Vida e Evolução">Ciências (EF) - Vida e Evolução</option>
<option value="Ciências (EF) - Terra e Universo">Ciências (EF) - Terra e Universo</option>
<option value="Física (EM) - Movimentos e forças">Física (EM) - Movimentos e forças</option>
<option value="Física (EM) - Energia e suas transformações">Física (EM) - Energia e suas transformações</option>
<option value="Física (EM) - Ondas e radiação">Física (EM) - Ondas e radiação</option>
<option value="Química (EM) - Matéria e suas transformações">Química (EM) - Matéria e suas transformações</option>
<option value="Química (EM) - Energia e suas transformações">Química (EM) - Energia e suas transformações</option>
<option value="Química (EM) - Química e sociedade">Química (EM) - Química e sociedade</option>
<option value="Biologia (EM) - Vida e evolução">Biologia (EM) - Vida e evolução</option>
<option value="Biologia (EM) - Corpo humano e saúde">Biologia (EM) - Corpo humano e saúde</option>
<option value="Biologia (EM) - Ecologia e sustentabilidade">Biologia (EM) - Ecologia e sustentabilidade</option>
<option value="Geografia (EM) - Espaço geográfico">Geografia (EM) - Espaço geográfico</option>
<option value="Geografia (EM) - Globalização e desigualdades">Geografia (EM) - Globalização e desigualdades</option>
<option value="Geografia (EM) - Sustentabilidade">Geografia (EM) - Sustentabilidade</option>
<option value="História (EF) - Mundo pessoal: meu lugar no mundo">História (EF) - Mundo pessoal: meu lugar no mundo</option>
<option value="História (EF) - A invenção do mundo moderno">História (EF) - A invenção do mundo moderno</option>
<option value="História (EM) - Mundo contemporâneo">História (EM) - Mundo contemporâneo</option>
<option value="História (EM) - Brasil: formação e desafios">História (EM) - Brasil: formação e desafios</option>
<option value="Filosofia (EM) - Ética e política">Filosofia (EM) - Ética e política</option>
<option value="Filosofia (EM) - Teoria do conhecimento">Filosofia (EM) - Teoria do conhecimento</option>
<option value="Sociologia (EM) - Cultura e sociedade">Sociologia (EM) - Cultura e sociedade</option>
<option value="Sociologia (EM) - Trabalho e economia">Sociologia (EM) - Trabalho e economia</option>
<option value="Arte (EF) - Artes Visuais">Arte (EF) - Artes Visuais</option>
<option value="Arte (EF) - Dança">Arte (EF) - Dança</option>
<option value="Arte (EF) - Música">Arte (EF) - Música</option>
<option value="Educação Física (EF) - Brincadeiras e jogos">Educação Física (EF) - Brincadeiras e jogos</option>
<option value="Educação Física (EF) - Esportes">Educação Física (EF) - Esportes</option>
<option value="Geografia (EF) - Formas de representação e pensamento espacial">Geografia (EF) - Formas de representação e pensamento espacial</option>
<option value="Geografia (EF) - Natureza, ambientes e qualidade de vida">Geografia (EF) - Natureza, ambientes e qualidade de vida</option>
<option value="Geografia (EF) - O sujeito e seu lugar no mundo">Geografia (EF) - O sujeito e seu lugar no mundo</option>
<option value="Geografia (EF) - Conexões e escalas">Geografia (EF) - Conexões e escalas</option>
<option value="Geografia (EF) - Mundo do trabalho">Geografia (EF) - Mundo do trabalho</option>