<option value="Respeito à diversidade">
<option value="Corpo humano">
<option value="Reconstrução das condições de produção e recepção de textos">
<option value="Estratégia de leitura">
<option value="Planejamento de texto">
<option value="Revisão de textos">
<option value="Características da conversação espontânea">
<option value="Contagem de histórias">
<option value="Brincadeiras e jogos de matriz indígena e africana">
<option value="Lutas de matriz indígena e africana">
<option value="Esportes de combate">
<option value="Medidas de tempo: leitura de horas em relógios digitais e analógicos, duração de eventos e relações entre unidades de medida de tempo">
<option value="Problemas: adição e subtração de números naturais e números racionais cuja representação decimal é finita">
<option value="Figuras geométricas planas: características, representações e ângulos">
<option value="Aproximação de números para múltiplos de potências de 10">
<option value="Trabalho e inovação tecnológica">
<option value="Dinâmica populacional">
<option value="Gestão pública da qualidade de vida">
<option value="Biodiversidade e ciclo hidrológico">
<option value="Produção, circulação e consumo de mercadorias">
<option value="Corporações e organismos internacionais e do Brasil na ordem econômica mundial">
<option value="Identidades e interculturalidades regionais: Estados Unidos da América, América espanhola e portuguesa e África">
<option value="Cadeias industriais e inovação no uso dos recursos naturais e matérias-primas">
<option value="Leitura e elaboração de mapas temáticos, croquis e outras formas de representação para analisar informações geográficas">
<option value="Intercâmbios históricos e culturais entre Europa, Ásia e Oceania">
<option value="Identidades e interculturalidades regionais: continente americano">
<option value="A hegemonia europeia na economia, na política e na cultura">
<option value="A divisão do mundo em Ocidente e Oriente">
<option value="Corporações e organismos internacionais">
<option value="Integração mundial e suas interpretações: globalização e mundialização">
<option value="Diversidade ambiental e as transformações nas paisagens na Europa, na Ásia e na Oceania">
<option value="Hegemonia europeia na economia, na política e na cultura">
<option value="Transformações do espaço na sociedade urbano-industrial">
<option value="As manifestações culturais na formação populacional">